### PR TITLE
Set clear expectations wrt. interoperability. Fix #37.

### LINKED ISSUE #37: Interoperability
There should be a section in the charter on interoperability, stating what level of interoperability is being achieved with this proposed WG so that people have clear expectations of what this will and will not provide.

### PR DESCRIPTION
**Pull request by msporny**

### CODE REVIEW

**Review by jandrieu — APPROVED** [review]
This is a good adjustment. The working group will have to clearly define what interoperability means.

**Review by kimdhamilton — APPROVED** [review]
LGTM

**Comment by brentzundel** [comment]
How does this relate to PR #39 ?

**Review by burnburn — APPROVED** [review]

**Review by ken-ebert — APPROVED** [review]

**Comment by msporny** [comment]
We discussed this on the 2019-07-02 call adn the group agreed to merge this as soon as the merge conflicts are resolved. @brentzundel and @msporny will ensure that the final merged text is what was intended.

**Pull request merged**
