### PR TITLE
Add coordination groups. Fix #44.

### LINKED ISSUE #44: Coordination section needs more
The coordination section should add W3C working, interest, and community groups with whom the DIDWG will coordinate.

### PR DESCRIPTION
**Pull request by msporny**

### CODE REVIEW

**Comment by jandrieu** [comment]
Shouldn't we also say something about helping WebAuthN support DIDs and DID Documents as sources of keys for authentication?

**Comment by burnburn** [comment]
@jandrieu my first reaction to your suggestion was yes, but I suspect that will lead us down a rabbit hole of wording tweaks.

**Comment by jandrieu** [comment]
@burnburn Yeah. I had the same thought.  I'm good either with current language or something more, if the original author wanted to expand a bit.

**Comment by jandrieu** [comment]
In fact, re-reading the text, I like it just the way it is. 

+1 to merge

**Review by jandrieu — APPROVED** [review]
LGTM

**Review by brentzundel — APPROVED** [review]

**Review by ken-ebert — APPROVED** [review]

**Pull request merged**
