### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by TallTed**
* source-doc whitespace humanization
* punctuation and typo fixes

### CODE REVIEW

**Comment by msporny** [comment]
Duplicate of #31 and #40?

**Comment by TallTed** [comment]
As with #40. See a problem, fix a problem, not remembering that a fix is pending from weeks ago...

**Comment by msporny** [comment]
> As with #40. See a problem, fix a problem, not remembering that a fix is pending from weeks ago...

What do you want me to do here? Merge all three, merge two of three, merge one of them and close the other two?

In the future, the best way to address this is to do the clean up in *one* PR as that reduces the number of conflicts and makes it easier for me to make an "it's editorial, merging" decision.

**Comment by TallTed** [comment]
> the best way to address this is to do the clean up in _one_ PR

Well, yes, which I would have done had I remembered that (or thought to check whether) the earlier existed when I did the later...  

> What do you want me to do here? Merge all three, merge two of three, merge one of them and close the other two?

I think it'll be best to merge #31 (where I've now resolved the conflicts), let me resolve conflicts on #40, merge #40, let me resolve conflicts on #48, and merge #48.  I'll do my best to check for unmerged PRs before creating new ones going forward.

**Comment by msporny** [comment]
> I think it'll be best to merge #31 (where I've now resolved the conflicts), let me resolve conflicts on #40, merge #40, let me resolve conflicts on #48, and merge #48. I'll do my best to check for unmerged PRs before creating new ones going forward.

Great, thanks, I'll focus on #31 for now, then.

**Comment by msporny** [comment]
Ok, #30 is merged. Please fix merge conflicts for #40.

**Comment by msporny** [comment]
Ok, #40 is merged. Please fix merge conflicts for #48 (this PR).

**Comment by TallTed** [comment]
@msporny - I think this'll do it.

**Review by msporny — APPROVED** [review]
Editorial. Merging.

**Comment by msporny** [comment]
Great, thanks @TallTed! Going to go and tell everyone else to rebase their PRs now.

**Pull request merged**
