### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by TallTed**
* punctuation fixes
* (partial) markup rationalization

### CODE REVIEW

**Review by brentzundel — APPROVED** [review]

**Comment by msporny** [comment]
Wait a sec, is this a duplicate of #31?

**Comment by TallTed** [comment]
Not a duplicate, but it does overlap. A month's delay in merging PRs means that the same problem gets seen multiple times, and repeat PRs can be created because the earlier isn't remembered.

**Comment by TallTed** [comment]
@msporny - #40 conflicts resolved.

**Review by msporny — APPROVED** [review]
Merging, editorial.

**Pull request merged**
