### PR TITLE
Add reference to self-sovereign identity principles. Fix #46.

### LINKED ISSUE #46: add link to SSI principles
The "Self-Sovereign Principles" document has shaped much of the thought and direction of decentralized identifiers, so there should be a reference to it in the charter.

### PR DESCRIPTION
**Pull request by msporny**

### CODE REVIEW

**Review by jandrieu — APPROVED** [review]
This looks good to me. It's brief and to the point.

**Review by kimdhamilton — APPROVED** [review]
LGTM

**Review by peacekeeper — CHANGES_REQUESTED** [review]
Can we say ... Self-Sovereign Identity Principles **"that DIDs are intended to fulfill"** (or "support" or "enable") rather than **"that have influenced the direction of this work"** ?

**Review by burnburn — APPROVED** [review]
I am okay with either the original text or Markus' proposed modification.

**Review by brentzundel — APPROVED** [review]

**Review by ken-ebert — APPROVED** [review]

**Review by msporny — COMMENTED** [review]
The group discussed this on the 2019-07-02 call and agreed to the following text: Finally, there are a set of Self-Sovereign Identity Principles ￼that have guided the direction of this work. ... the group also agreed to use a hash-based link to the content so the context of the SSI principles won't change. Fix the PR and merge as soon as it's fixed.

https://github.com/WebOfTrustInfo/self-sovereign-identity/blob/d578197f51b4b7fa8bc9ed587b57bf8de04d7249/self-sovereign-identity-principles.md

**Pull request merged**
